# Dockerfile
FROM postgres:14.4-alpine

#ADD scripts/startup.sh /usr/sbin/startup.sh
#ADD scripts/drop-create-user.sh /tmp/drop-create-user.sh
#RUN chmod +x /usr/sbin/startup.sh
#RUN chmod +x /tmp/drop-create-user.sh
